### ISSUE TITLE
Mistake in SimpleListAdapter get item

### ISSUE THREAD

**Issue by NivaLevy** [michaelprimez/searchablespinner#11]
@Override
    public Object getItem(int position) {
        if (mStrings == null && position > 0) 
            return mStrings.get(position);
        else
            return null;
    }
*********should be:****
 @Override
    **public Object getItem(int position) {
        if (mStrings != null && position > 0) 
            return mStrings.get(position - 1);
        else
            return null;
    }**

**Comment by pharma-vie** [comment]
There is another error somewhere in the code, So that even with this code, the "no selection" always displays in myTextView the value number 1 instead it should be 0 or null and it does not display anything.

**Comment by michaelprimez** [comment]
Hi @NivaLevy  

Thanks for using the library, yes you right, it's a mistake i fix it
