### ISSUE TITLE
How to create methode : Spinner on Searchable Item Clicked.

### ISSUE THREAD

**Issue by pharma-vie** [michaelprimez/searchablespinner#13]
Plz help me...

**Comment by michaelprimez** [comment]
Hi @pharma-vie 

If you want to take the selected value when you submit a form you can use the 
```
mSearchableSpinner.getSelectedItem()
```

if you really need to monitor the selected item you can use the 
```
mSearchableSpinner.setOnItemSelectedListener(mOnItemSelectedListener);
```
as exists in the example project.

Thanks for using the lib.

**Comment by pharma-vie** [comment]
thinks micheal
i have two spinner 
The second spinner is based on the selection of the first spinner
lorsque on fait la recherche sur le spinner1
spinner1.OnItemSelectedListener
la valeur affiché sur le spinner2 est celle de la position 0 et non la position exact par example la position reel qui est 5.
