### ISSUE TITLE
I can't add my items into it

### ISSUE THREAD

**Issue by JAOOOOO** [michaelprimez/searchablespinner#15]
i couldn't add my data into it using ArrayAdapter

**Comment by michaelprimez** [comment]
I update the example application with an ArrayAdapter use case and i don't see any problem. Can you give me more details please.

**Comment by JAOOOOO** [comment]
Hello , I think it will be so much better , if the search is based on
.contains() instead of .startWith()

Thank you

**Comment by michaelprimez** [comment]
The adapter and the filter implementation is not library related. The implementation depend of what type of items the spinner could hold. Thus, is up to the programmer that use the library to implement the filter.
