### ISSUE TITLE
No Selection window API 21

### ISSUE THREAD

**Issue by mitulpanch** [michaelprimez/searchablespinner#17]
Api Level - 21
model - Lenovo 6000
Selection window is not coming incase if i apply attribute
app:SpinnerExpandHeight="100dp" (>0dp)

its visible if i write 
app:SpinnerExpandHeight="0dp"

Any suggesstion?
its visible in other API levels

**Comment by michaelprimez** [comment]
Hi @mitulpanch, you right i manage to reproduce it and I already fix it but it will be available soon, in the next release of the library.

**Comment by giaur500** [comment]
@michaelprimez as I can see, you are using some animation api (it should be disabled for <21) and also you used edit library that again needs api 21 (reason is the same, animation api)
