### ISSUE TITLE
How to set items when spinner is loaded?

### ISSUE THREAD

**Issue by arunarajput** [michaelprimez/searchablespinner#19]
Currently when I click on spinner icon then respective list is showing but when spinner is loaded so spinner list items are showing only when click on spinner but i want to show as default value on visible items means 0th postion. Actually it is showing blank. Please help me how to replace "Touch to select" text to list items???

**Comment by michaelprimez** [comment]
I am not sure what exactly you want to do :( but if you want to replace the  "Touch to select" with some other text you can use the RevealEmptyText property in your xml.
```
app:RevealEmptyText="Touch to select"
```
Also, if you want to replace the Search hint you can use the SearchHintText property
```
app:SearchHintText="Search Hint Text"
```
Otherwise, please give me an example of what exactly the "Touch to select" should be replaced.

**Comment by arunarajput** [comment]
No I want to replace "Touch to select" with my list item which is on 0th postion.

**Comment by michaelprimez** [comment]
Then, you can use the 
```
mSearchableSpinner.setSelectedItem(0);
```
or 
```
mSearchableSpinner.setSelectedItem(1);
```
if in your adapter you have "No Selection" in the first place.

**Comment by arunarajput** [comment]
Before setAdapter or after setAdapter ? Which one is correct?

**Comment by michaelprimez** [comment]
After set adapter. otherwise the spinner doesn't have any item to show.

**Comment by arunarajput** [comment]
correct...Thanks..Can you please answer the second query?

**Comment by arunarajput** [comment]
Can you please help me?

**Comment by michaelprimez** [comment]
This has to do with how Android/Spinner works. Also simple Android spinner have this behavior, the onItemSelected runs on Activity/Fragments load.

**Comment by arunarajput** [comment]
so this behavior is not available in this library?

**Comment by michaelprimez** [comment]
It's not library specific. You can find a lot of references on StackOverflow about how you can prevent the Android/Spinner onItemSelected to run when Activity/Fragment is loaded.

Thanks that using the library.

**Comment by arunarajput** [comment]
When I use android spinner then setOnItemSelectedListener() being called but when I use your searchable spinner then setOnItemSelectedListener() not called. what is the problem?

**Comment by arunarajput** [comment]
Is there any solution?

**Comment by michaelprimez** [comment]
There isn't any problem, I don't use any Spinner in the library so when you register a listener you actually register a listener to a ListView witch it has different behavior. If you want to do anything when the Activity/Fragment starts, you can do it inside onCreate/onResume using Searchable Spinner methods.

**Comment by arunarajput** [comment]
I mean when I use your searchable spinner so setOnItemSelectedListener() not being called.
