### ISSUE TITLE
hello dear

### ISSUE THREAD

**Issue by moh241eng** [michaelprimez/searchablespinner#2]
i have issue 

can you help me  
Error:Unable to find method 'org.gradle.api.tasks.Sync.getInputs()Lorg/gradle/api/internal/TaskInputsInternal;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

thank you for your time

**Comment by michaelprimez** [comment]
Hi,
Can you tell please what version of gradle wrapper do you use ?

Keep in mind those StackOverflow posts
http://stackoverflow.com/questions/41116687/gradle-build-failing-after-update-to-android-studio-2-3-canary-3
http://stackoverflow.com/questions/41152475/failed-gradle-sync

**Comment by michaelprimez** [comment]
Hey @moh241eng, did you solve it? I guess yes and i close the issue and if you have new information you can reopen it.
Thanks

**Comment by moh241eng** [comment]
thank you dear
