### ISSUE TITLE
hide dialog onbackpressed

### ISSUE THREAD

**Issue by abbasalim** [michaelprimez/searchablespinner#23]
how can set hide dialog onbackpressed, or check if is open ,close it
also open keyboard when open spinner dialog

**Comment by abbasalim** [comment]
i open keyboard 
` sp_customer.setStatusListener(new IStatusListener() {
            @Override
            public void spinnerIsOpening() {
                Extra.showSoftKeyboard(sp_customer.findViewById(gr.escsoft.michaelprimez.searchablespinner.R.id.EdtTxt_SearchEditText),FactorActivity.this);
            }

            @Override
            public void spinnerIsClosing() {

            }
        });`

**Comment by michaelprimez** [comment]
Hi,
The keyboard is opening and closing when the user tap to the edit view for a search.
In the example application in the MainActivity.java i put some examples of how you can achieve this behavior.

```
@Override
    public boolean onTouchEvent(MotionEvent event) {
        if (!mSearchableSpinner.isInsideSearchEditText(event)) {
            mSearchableSpinner.hideEdit();
        }
        if (!mSearchableSpinner1.isInsideSearchEditText(event)) {
            mSearchableSpinner1.hideEdit();
        }
        if (!mSearchableSpinner2.isInsideSearchEditText(event)) {
            mSearchableSpinner2.hideEdit();
        }
        return super.onTouchEvent(event);
    }
```

and also, as you figure it out the below code close the keyboard 

```
mSearchableSpinner3.setStatusListener(new IStatusListener() {
            @Override
            public void spinnerIsOpening() {
               // Put your show keyboard here 
               Extra.showSoftKeyboard
            }

            @Override
            public void spinnerIsClosing() {

            }
        });
```

For the back press you must overwrite the activity's onBackPress and use the hideEdit.
