### ISSUE TITLE
How to add Items to your Searchable Spinner

### ISSUE THREAD

**Issue by spitzlitz** [michaelprimez/searchablespinner#25]
Hello,

i am from Germany (my english is not so good) and want to add your searchable spinner in my app.
I use "Android Studio" and do it like your instruction "usage":
1. Add the dependency to your build.gradle.
2. Usage on layout

=That works.

Now i want to add items to the searchable Spinner, but either my app crash or the searchable spinner stays empty. 

Have you a tip for my?

Best regards 
Andreas

**Comment by michaelprimez** [comment]
Hi
Did you check out the examples in 
https://github.com/michaelprimez/searchablespinner/blob/master/app/src/main/java/gr/escsoft/michaelprimez/searchablespinnerexamples/MainActivity.java ?

**Comment by spitzlitz** [comment]
Hi,

i try but its hard to copy all codes in my project.


Now i fail at: mSearchableSpinner.setAdapter(mSimpleArrayListAdapter);

with Error:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void gr.escsoft.michaelprimez.searchablespinner.SearchableSpinner.setAdapter(android.widget.ListAdapter)' on a null object reference`
