### ISSUE TITLE
It requires inadequate libraries

### ISSUE THREAD

**Issue by AlMel3000** [michaelprimez/searchablespinner#3]
Hello!
First of all it required last support repository version. Ok, I've updated it.
Now it requires constraint-layout:1.0.0-beta4.

Error:Could not find com.android.support.constraint:constraint-layout:1.0.0-beta4.
Required by:
    penpa:app:unspecified > gr.escsoft.michaelprimez.searchablespinner:SearchableSpinner:1.0.1
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by michaelprimez** [comment]
Hi
I removed the unnecessary constraint-layout.
You can try now with version 1.0.2.

Thanks
