### ISSUE TITLE
Spinner selection dialog not closed when we moved to next screen

### ISSUE THREAD

**Issue by jestopaul** [michaelprimez/searchablespinner#35]
In my app i have 3 screen .First screen i am implement searchable spinner .Then search some keywords in popup window .shows some searchable result.Then i am not selected any item .Popup still showing.Then i moved to second screen,but spinner popup showing there. Not closed automatically. How to manage it?
Please help.

**Comment by gustinoco** [comment]
Use the property   mSpinner.hideEdit();  when advance screen. 
If you open Spinner and use the button onback, use hideEdit() in onDestroyView.
