### ISSUE TITLE
How to reset to select 

### ISSUE THREAD

**Issue by sameer715** [michaelprimez/searchablespinner#4]
How to reset the spinner from selected value to select on an event for e.g. change in items of list

**Comment by michaelprimez** [comment]
Hi, 
the 1.0.3 version allow you to set the selected item, if you put in your code setSelectedItem(-1) the spinner resets to whatever the "RevealEmptyText" is setup. Also, the example project now contain an adapter allowing user to select nothing.
If this is what you looking for please close the issue.

thanks

**Comment by sameer715** [comment]
Thanks man you are great! Keep up this great work.

**Comment by justrelax19** [comment]
setSelectedItem(-1) is giving array out of bound exception error.
How to fix it
