### ISSUE TITLE
Its having release time null pointer exception

### ISSUE THREAD

**Issue by sunilash143** [michaelprimez/searchablespinner#7]
Its having release time null pointer exception why it comes

**Comment by michaelprimez** [comment]
Hi @sunilash143 

What version do you use?
Can you be more specific?

Thanks

**Comment by sunilash143** [comment]
I have solve this problem but can you please suggest me if my version level
is 15 then not working.

-- 
Kind Regards

*Sunil Khandekar*
Pune, India
Mob.: +91 9762251042 | 9403031450
Email :pappuash.khandekar2@gmail.com

**Comment by michaelprimez** [comment]
Hi @sunilash143 

Unfortunately the library has minSdkVersion = 21 and doesn't support lower sdk versions.

Thanks
