### ISSUE TITLE
Size and position of drop down list

### ISSUE THREAD

**Issue by Elessawy** [michaelprimez/searchablespinner#8]
Hi @michaelprimez 

The drop down list is not as the same size and position of the spinner it self. As you see in the image, I use the spinner in an arabic application and I don't know if it's the reason of this problem.

Is there any method to set the width and the position of the drop down list?

![test](https://cloud.githubusercontent.com/assets/12501248/24096906/3d272820-0d6c-11e7-8270-0bce6ab9a535.png)

Again, thanks for your efforts in this amazing library and for your fast response.

**Comment by PatilAbhi** [comment]
Did You Know how to divide the content in the spinner

**Comment by michaelprimez** [comment]
Hi @PatilAbhi 

Can you please post the xml in order to reproduce it. Thanks

**Comment by PatilAbhi** [comment]
<gr.escsoft.michaelprimez.searchablespinner.SearchableSpinner
                android:id="@+id/spinner1"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:textSize="20sp"
                android:gravity="center_horizontal"
                app:DoneSearchTintColor="@android:color/holo_purple"
                app:RevealEmptyText="   Touch to select"
                app:RevealViewBackgroundColor="@android:color/holo_purple"
                app:SearchViewBackgroundColor="@android:color/secondary_text_dark"
                app:ShowBorders="false"
                app:SpinnerExpandHeight="200dp"
                app:StartSearchTintColor="@android:color/white"
                app:hintText="Select Fault" />

**Comment by PatilAbhi** [comment]
I want to divide the items with a horizontal line ...

**Comment by michaelprimez** [comment]
Hi @PatilAbhi 

about the items divider you can use the version 1.0.8 which it has 2 new properties ItemsDivider and DividerHeight. About the size and position of the list, i can't reproduce it, maybe something is wrong in your adapter's item creation or somewhere in the layout a margin or padding breaks the view. It would be very helpful if you post the layout that's include the spinner and the getView code from the adapter.

Thanks.

**Comment by Elessawy** [comment]
Hi @michaelprimez 
Is there any solution for the main issue?
"Is there any method to set the width and the position of the drop down list?"
Thanks in advance.

**Comment by michaelprimez** [comment]
Hey @Elessawy 

i saw in the picture that the arrow icon is at the left, What did you do and you mange to place it here, maybe that's causing the problem.

**Comment by Elessawy** [comment]
I changed the localization of the whole app to arabic and by default some components like spinners flips horizontally because arabic language is written from the right to the left.

For example, this is the position of back button after changing the localization

**Comment by Elessawy** [comment]
I changed the localization of the whole app to arabic and by default some components like spinners flips horizontally because arabic language is written from the right to the left.

For example, this is the position of back button after changing the localization

**Comment by Elessawy** [comment]
I changed the localization of the whole app to arabic and by default some components like spinners flips horizontally because arabic language is written from the right to the left.

For example, this is the position of back button after changing the localization

![17453579_10212532535806054_2125845979_o](https://cloud.githubusercontent.com/assets/12501248/24169243/a9e672e4-0e85-11e7-8002-f7b63c2c6c1e.jpg)

**Comment by michaelprimez** [comment]
Hi @Elessawy 

I know am late but i response. I think i solve the issue in version 1.0.9.

Thanks

**Comment by Elessawy** [comment]
Thanks
